# Generated by Django 4.1.1 on 2022-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'logsModel',
                'verbose_name_plural': 'logsModels',
            },
        ),
    ]
