# Generated by Django 4.1.1 on 2022-10-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsmodel',
            name='method',
        ),
        migrations.RemoveField(
            model_name='logsmodel',
            name='path',
        ),
    ]
